import { HeroMetadata } from "../types/dota";

const VALVE_HERO_IMG_BASE = "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes";

export const HEROES_MAP: Record<number, HeroMetadata> = {
  1: {
    id: 1,
    name: "npc_dota_hero_antimage",
    shortName: "antimage",
    displayName: "Anti-Mage",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/antimage.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/antimage.png`,
  },
  2: {
    id: 2,
    name: "npc_dota_hero_axe",
    shortName: "axe",
    displayName: "Axe",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/axe.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/axe.png`,
  },
  3: {
    id: 3,
    name: "npc_dota_hero_bane",
    shortName: "bane",
    displayName: "Bane",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/bane.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/bane.png`,
  },
  4: {
    id: 4,
    name: "npc_dota_hero_bloodseeker",
    shortName: "bloodseeker",
    displayName: "Bloodseeker",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/bloodseeker.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/bloodseeker.png`,
  },
  5: {
    id: 5,
    name: "npc_dota_hero_crystal_maiden",
    shortName: "crystal_maiden",
    displayName: "Crystal Maiden",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/crystal_maiden.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/crystal_maiden.png`,
  },
  6: {
    id: 6,
    name: "npc_dota_hero_drow_ranger",
    shortName: "drow_ranger",
    displayName: "Drow Ranger",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/drow_ranger.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/drow_ranger.png`,
  },
  7: {
    id: 7,
    name: "npc_dota_hero_earthshaker",
    shortName: "earthshaker",
    displayName: "Earthshaker",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/earthshaker.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/earthshaker.png`,
  },
  8: {
    id: 8,
    name: "npc_dota_hero_juggernaut",
    shortName: "juggernaut",
    displayName: "Juggernaut",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/juggernaut.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/juggernaut.png`,
  },
  9: {
    id: 9,
    name: "npc_dota_hero_mirana",
    shortName: "mirana",
    displayName: "Mirana",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/mirana.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/mirana.png`,
  },
  10: {
    id: 10,
    name: "npc_dota_hero_morphling",
    shortName: "morphling",
    displayName: "Morphling",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/morphling.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/morphling.png`,
  },
  11: {
    id: 11,
    name: "npc_dota_hero_nevermore",
    shortName: "nevermore",
    displayName: "Shadow Fiend",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/nevermore.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/nevermore.png`,
  },
  12: {
    id: 12,
    name: "npc_dota_hero_phantom_lancer",
    shortName: "phantom_lancer",
    displayName: "Phantom Lancer",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/phantom_lancer.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/phantom_lancer.png`,
  },
  13: {
    id: 13,
    name: "npc_dota_hero_puck",
    shortName: "puck",
    displayName: "Puck",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/puck.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/puck.png`,
  },
  14: {
    id: 14,
    name: "npc_dota_hero_pudge",
    shortName: "pudge",
    displayName: "Pudge",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/pudge.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/pudge.png`,
  },
  15: {
    id: 15,
    name: "npc_dota_hero_razor",
    shortName: "razor",
    displayName: "Razor",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/razor.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/razor.png`,
  },
  16: {
    id: 16,
    name: "npc_dota_hero_sand_king",
    shortName: "sand_king",
    displayName: "Sand King",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/sand_king.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/sand_king.png`,
  },
  17: {
    id: 17,
    name: "npc_dota_hero_storm_spirit",
    shortName: "storm_spirit",
    displayName: "Storm Spirit",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/storm_spirit.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/storm_spirit.png`,
  },
  18: {
    id: 18,
    name: "npc_dota_hero_sven",
    shortName: "sven",
    displayName: "Sven",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/sven.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/sven.png`,
  },
  19: {
    id: 19,
    name: "npc_dota_hero_tiny",
    shortName: "tiny",
    displayName: "Tiny",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/tiny.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/tiny.png`,
  },
  20: {
    id: 20,
    name: "npc_dota_hero_vengefulspirit",
    shortName: "vengefulspirit",
    displayName: "Vengeful Spirit",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/vengefulspirit.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/vengefulspirit.png`,
  },
  21: {
    id: 21,
    name: "npc_dota_hero_windrunner",
    shortName: "windrunner",
    displayName: "Windranger",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/windrunner.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/windrunner.png`,
  },
  22: {
    id: 22,
    name: "npc_dota_hero_zuus",
    shortName: "zuus",
    displayName: "Zeus",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/zuus.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/zuus.png`,
  },
  23: {
    id: 23,
    name: "npc_dota_hero_kunkka",
    shortName: "kunkka",
    displayName: "Kunkka",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/kunkka.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/kunkka.png`,
  },
  25: {
    id: 25,
    name: "npc_dota_hero_lina",
    shortName: "lina",
    displayName: "Lina",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/lina.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/lina.png`,
  },
  26: {
    id: 26,
    name: "npc_dota_hero_lion",
    shortName: "lion",
    displayName: "Lion",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/lion.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/lion.png`,
  },
  27: {
    id: 27,
    name: "npc_dota_hero_shadow_shaman",
    shortName: "shadow_shaman",
    displayName: "Shadow Shaman",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/shadow_shaman.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/shadow_shaman.png`,
  },
  28: {
    id: 28,
    name: "npc_dota_hero_slardar",
    shortName: "slardar",
    displayName: "Slardar",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/slardar.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/slardar.png`,
  },
  29: {
    id: 29,
    name: "npc_dota_hero_tidehunter",
    shortName: "tidehunter",
    displayName: "Tidehunter",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/tidehunter.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/tidehunter.png`,
  },
  30: {
    id: 30,
    name: "npc_dota_hero_witch_doctor",
    shortName: "witch_doctor",
    displayName: "Witch Doctor",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/witch_doctor.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/witch_doctor.png`,
  },
  31: {
    id: 31,
    name: "npc_dota_hero_lich",
    shortName: "lich",
    displayName: "Lich",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/lich.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/lich.png`,
  },
  32: {
    id: 32,
    name: "npc_dota_hero_riki",
    shortName: "riki",
    displayName: "Riki",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/riki.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/riki.png`,
  },
  33: {
    id: 33,
    name: "npc_dota_hero_enigma",
    shortName: "enigma",
    displayName: "Enigma",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/enigma.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/enigma.png`,
  },
  34: {
    id: 34,
    name: "npc_dota_hero_tinker",
    shortName: "tinker",
    displayName: "Tinker",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/tinker.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/tinker.png`,
  },
  35: {
    id: 35,
    name: "npc_dota_hero_sniper",
    shortName: "sniper",
    displayName: "Sniper",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/sniper.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/sniper.png`,
  },
  36: {
    id: 36,
    name: "npc_dota_hero_necrolyte",
    shortName: "necrolyte",
    displayName: "Necrophos",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/necrolyte.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/necrolyte.png`,
  },
  37: {
    id: 37,
    name: "npc_dota_hero_warlock",
    shortName: "warlock",
    displayName: "Warlock",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/warlock.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/warlock.png`,
  },
  38: {
    id: 38,
    name: "npc_dota_hero_beastmaster",
    shortName: "beastmaster",
    displayName: "Beastmaster",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/beastmaster.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/beastmaster.png`,
  },
  39: {
    id: 39,
    name: "npc_dota_hero_queenofpain",
    shortName: "queenofpain",
    displayName: "Queen of Pain",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/queenofpain.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/queenofpain.png`,
  },
  40: {
    id: 40,
    name: "npc_dota_hero_venomancer",
    shortName: "venomancer",
    displayName: "Venomancer",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/venomancer.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/venomancer.png`,
  },
  41: {
    id: 41,
    name: "npc_dota_hero_faceless_void",
    shortName: "faceless_void",
    displayName: "Faceless Void",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/faceless_void.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/faceless_void.png`,
  },
  42: {
    id: 42,
    name: "npc_dota_hero_skeleton_king",
    shortName: "skeleton_king",
    displayName: "Wraith King",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/skeleton_king.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/skeleton_king.png`,
  },
  43: {
    id: 43,
    name: "npc_dota_hero_death_prophet",
    shortName: "death_prophet",
    displayName: "Death Prophet",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/death_prophet.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/death_prophet.png`,
  },
  44: {
    id: 44,
    name: "npc_dota_hero_phantom_assassin",
    shortName: "phantom_assassin",
    displayName: "Phantom Assassin",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/phantom_assassin.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/phantom_assassin.png`,
  },
  45: {
    id: 45,
    name: "npc_dota_hero_pugna",
    shortName: "pugna",
    displayName: "Pugna",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/pugna.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/pugna.png`,
  },
  46: {
    id: 46,
    name: "npc_dota_hero_templar_assassin",
    shortName: "templar_assassin",
    displayName: "Templar Assassin",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/templar_assassin.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/templar_assassin.png`,
  },
  47: {
    id: 47,
    name: "npc_dota_hero_viper",
    shortName: "viper",
    displayName: "Viper",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/viper.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/viper.png`,
  },
  48: {
    id: 48,
    name: "npc_dota_hero_luna",
    shortName: "luna",
    displayName: "Luna",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/luna.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/luna.png`,
  },
  49: {
    id: 49,
    name: "npc_dota_hero_dragon_knight",
    shortName: "dragon_knight",
    displayName: "Dragon Knight",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/dragon_knight.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/dragon_knight.png`,
  },
  50: {
    id: 50,
    name: "npc_dota_hero_dazzle",
    shortName: "dazzle",
    displayName: "Dazzle",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/dazzle.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/dazzle.png`,
  },
  51: {
    id: 51,
    name: "npc_dota_hero_rattletrap",
    shortName: "rattletrap",
    displayName: "Clockwerk",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/rattletrap.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/rattletrap.png`,
  },
  52: {
    id: 52,
    name: "npc_dota_hero_leshrac",
    shortName: "leshrac",
    displayName: "Leshrac",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/leshrac.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/leshrac.png`,
  },
  53: {
    id: 53,
    name: "npc_dota_hero_furion",
    shortName: "furion",
    displayName: "Nature's Prophet",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/furion.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/furion.png`,
  },
  54: {
    id: 54,
    name: "npc_dota_hero_life_stealer",
    shortName: "life_stealer",
    displayName: "Lifestealer",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/life_stealer.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/life_stealer.png`,
  },
  55: {
    id: 55,
    name: "npc_dota_hero_dark_seer",
    shortName: "dark_seer",
    displayName: "Dark Seer",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/dark_seer.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/dark_seer.png`,
  },
  56: {
    id: 56,
    name: "npc_dota_hero_clinkz",
    shortName: "clinkz",
    displayName: "Clinkz",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/clinkz.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/clinkz.png`,
  },
  57: {
    id: 57,
    name: "npc_dota_hero_omniknight",
    shortName: "omniknight",
    displayName: "Omniknight",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/omniknight.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/omniknight.png`,
  },
  58: {
    id: 58,
    name: "npc_dota_hero_enchantress",
    shortName: "enchantress",
    displayName: "Enchantress",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/enchantress.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/enchantress.png`,
  },
  59: {
    id: 59,
    name: "npc_dota_hero_huskar",
    shortName: "huskar",
    displayName: "Huskar",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/huskar.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/huskar.png`,
  },
  60: {
    id: 60,
    name: "npc_dota_hero_night_stalker",
    shortName: "night_stalker",
    displayName: "Night Stalker",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/night_stalker.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/night_stalker.png`,
  },
  61: {
    id: 61,
    name: "npc_dota_hero_broodmother",
    shortName: "broodmother",
    displayName: "Broodmother",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/broodmother.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/broodmother.png`,
  },
  62: {
    id: 62,
    name: "npc_dota_hero_bounty_hunter",
    shortName: "bounty_hunter",
    displayName: "Bounty Hunter",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/bounty_hunter.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/bounty_hunter.png`,
  },
  63: {
    id: 63,
    name: "npc_dota_hero_weaver",
    shortName: "weaver",
    displayName: "Weaver",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/weaver.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/weaver.png`,
  },
  64: {
    id: 64,
    name: "npc_dota_hero_jakiro",
    shortName: "jakiro",
    displayName: "Jakiro",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/jakiro.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/jakiro.png`,
  },
  65: {
    id: 65,
    name: "npc_dota_hero_batrider",
    shortName: "batrider",
    displayName: "Batrider",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/batrider.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/batrider.png`,
  },
  66: {
    id: 66,
    name: "npc_dota_hero_chen",
    shortName: "chen",
    displayName: "Chen",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/chen.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/chen.png`,
  },
  67: {
    id: 67,
    name: "npc_dota_hero_spectre",
    shortName: "spectre",
    displayName: "Spectre",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/spectre.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/spectre.png`,
  },
  68: {
    id: 68,
    name: "npc_dota_hero_ancient_apparition",
    shortName: "ancient_apparition",
    displayName: "Ancient Apparition",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/ancient_apparition.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/ancient_apparition.png`,
  },
  69: {
    id: 69,
    name: "npc_dota_hero_doom_bringer",
    shortName: "doom_bringer",
    displayName: "Doom",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/doom_bringer.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/doom_bringer.png`,
  },
  70: {
    id: 70,
    name: "npc_dota_hero_ursa",
    shortName: "ursa",
    displayName: "Ursa",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/ursa.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/ursa.png`,
  },
  71: {
    id: 71,
    name: "npc_dota_hero_spirit_breaker",
    shortName: "spirit_breaker",
    displayName: "Spirit Breaker",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/spirit_breaker.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/spirit_breaker.png`,
  },
  72: {
    id: 72,
    name: "npc_dota_hero_gyrocopter",
    shortName: "gyrocopter",
    displayName: "Gyrocopter",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/gyrocopter.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/gyrocopter.png`,
  },
  73: {
    id: 73,
    name: "npc_dota_hero_alchemist",
    shortName: "alchemist",
    displayName: "Alchemist",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/alchemist.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/alchemist.png`,
  },
  74: {
    id: 74,
    name: "npc_dota_hero_invoker",
    shortName: "invoker",
    displayName: "Invoker",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/invoker.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/invoker.png`,
  },
  75: {
    id: 75,
    name: "npc_dota_hero_silencer",
    shortName: "silencer",
    displayName: "Silencer",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/silencer.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/silencer.png`,
  },
  76: {
    id: 76,
    name: "npc_dota_hero_obsidian_destroyer",
    shortName: "obsidian_destroyer",
    displayName: "Outworld Destroyer",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/obsidian_destroyer.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/obsidian_destroyer.png`,
  },
  77: {
    id: 77,
    name: "npc_dota_hero_lycan",
    shortName: "lycan",
    displayName: "Lycan",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/lycan.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/lycan.png`,
  },
  78: {
    id: 78,
    name: "npc_dota_hero_brewmaster",
    shortName: "brewmaster",
    displayName: "Brewmaster",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/brewmaster.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/brewmaster.png`,
  },
  79: {
    id: 79,
    name: "npc_dota_hero_shadow_demon",
    shortName: "shadow_demon",
    displayName: "Shadow Demon",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/shadow_demon.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/shadow_demon.png`,
  },
  80: {
    id: 80,
    name: "npc_dota_hero_lone_druid",
    shortName: "lone_druid",
    displayName: "Lone Druid",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/lone_druid.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/lone_druid.png`,
  },
  81: {
    id: 81,
    name: "npc_dota_hero_chaos_knight",
    shortName: "chaos_knight",
    displayName: "Chaos Knight",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/chaos_knight.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/chaos_knight.png`,
  },
  82: {
    id: 82,
    name: "npc_dota_hero_meepo",
    shortName: "meepo",
    displayName: "Meepo",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/meepo.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/meepo.png`,
  },
  83: {
    id: 83,
    name: "npc_dota_hero_treant",
    shortName: "treant",
    displayName: "Treant Protector",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/treant.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/treant.png`,
  },
  84: {
    id: 84,
    name: "npc_dota_hero_ogre_magi",
    shortName: "ogre_magi",
    displayName: "Ogre Magi",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/ogre_magi.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/ogre_magi.png`,
  },
  85: {
    id: 85,
    name: "npc_dota_hero_undying",
    shortName: "undying",
    displayName: "Undying",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/undying.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/undying.png`,
  },
  86: {
    id: 86,
    name: "npc_dota_hero_rubick",
    shortName: "rubick",
    displayName: "Rubick",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/rubick.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/rubick.png`,
  },
  87: {
    id: 87,
    name: "npc_dota_hero_disruptor",
    shortName: "disruptor",
    displayName: "Disruptor",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/disruptor.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/disruptor.png`,
  },
  88: {
    id: 88,
    name: "npc_dota_hero_nyx_assassin",
    shortName: "nyx_assassin",
    displayName: "Nyx Assassin",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/nyx_assassin.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/nyx_assassin.png`,
  },
  89: {
    id: 89,
    name: "npc_dota_hero_naga_siren",
    shortName: "naga_siren",
    displayName: "Naga Siren",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/naga_siren.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/naga_siren.png`,
  },
  90: {
    id: 90,
    name: "npc_dota_hero_keeper_of_the_light",
    shortName: "keeper_of_the_light",
    displayName: "Keeper of the Light",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/keeper_of_the_light.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/keeper_of_the_light.png`,
  },
  91: {
    id: 91,
    name: "npc_dota_hero_wisp",
    shortName: "wisp",
    displayName: "Io",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/wisp.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/wisp.png`,
  },
  92: {
    id: 92,
    name: "npc_dota_hero_visage",
    shortName: "visage",
    displayName: "Visage",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/visage.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/visage.png`,
  },
  93: {
    id: 93,
    name: "npc_dota_hero_slark",
    shortName: "slark",
    displayName: "Slark",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/slark.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/slark.png`,
  },
  94: {
    id: 94,
    name: "npc_dota_hero_medusa",
    shortName: "medusa",
    displayName: "Medusa",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/medusa.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/medusa.png`,
  },
  95: {
    id: 95,
    name: "npc_dota_hero_troll_warlord",
    shortName: "troll_warlord",
    displayName: "Troll Warlord",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/troll_warlord.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/troll_warlord.png`,
  },
  96: {
    id: 96,
    name: "npc_dota_hero_centaur",
    shortName: "centaur",
    displayName: "Centaur Warrunner",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/centaur.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/centaur.png`,
  },
  97: {
    id: 97,
    name: "npc_dota_hero_magnataur",
    shortName: "magnataur",
    displayName: "Magnus",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/magnataur.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/magnataur.png`,
  },
  98: {
    id: 98,
    name: "npc_dota_hero_shredder",
    shortName: "shredder",
    displayName: "Timbersaw",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/shredder.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/shredder.png`,
  },
  99: {
    id: 99,
    name: "npc_dota_hero_bristleback",
    shortName: "bristleback",
    displayName: "Bristleback",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/bristleback.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/bristleback.png`,
  },
  100: {
    id: 100,
    name: "npc_dota_hero_tusk",
    shortName: "tusk",
    displayName: "Tusk",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/tusk.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/tusk.png`,
  },
  101: {
    id: 101,
    name: "npc_dota_hero_skywrath_mage",
    shortName: "skywrath_mage",
    displayName: "Skywrath Mage",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/skywrath_mage.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/skywrath_mage.png`,
  },
  102: {
    id: 102,
    name: "npc_dota_hero_abaddon",
    shortName: "abaddon",
    displayName: "Abaddon",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/abaddon.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/abaddon.png`,
  },
  103: {
    id: 103,
    name: "npc_dota_hero_elder_titan",
    shortName: "elder_titan",
    displayName: "Elder Titan",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/elder_titan.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/elder_titan.png`,
  },
  104: {
    id: 104,
    name: "npc_dota_hero_legion_commander",
    shortName: "legion_commander",
    displayName: "Legion Commander",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/legion_commander.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/legion_commander.png`,
  },
  105: {
    id: 105,
    name: "npc_dota_hero_techies",
    shortName: "techies",
    displayName: "Techies",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/techies.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/techies.png`,
  },
  106: {
    id: 106,
    name: "npc_dota_hero_ember_spirit",
    shortName: "ember_spirit",
    displayName: "Ember Spirit",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/ember_spirit.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/ember_spirit.png`,
  },
  107: {
    id: 107,
    name: "npc_dota_hero_earth_spirit",
    shortName: "earth_spirit",
    displayName: "Earth Spirit",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/earth_spirit.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/earth_spirit.png`,
  },
  108: {
    id: 108,
    name: "npc_dota_hero_abyssal_underlord",
    shortName: "abyssal_underlord",
    displayName: "Underlord",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/abyssal_underlord.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/abyssal_underlord.png`,
  },
  109: {
    id: 109,
    name: "npc_dota_hero_terrorblade",
    shortName: "terrorblade",
    displayName: "Terrorblade",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/terrorblade.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/terrorblade.png`,
  },
  110: {
    id: 110,
    name: "npc_dota_hero_phoenix",
    shortName: "phoenix",
    displayName: "Phoenix",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/phoenix.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/phoenix.png`,
  },
  111: {
    id: 111,
    name: "npc_dota_hero_oracle",
    shortName: "oracle",
    displayName: "Oracle",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/oracle.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/oracle.png`,
  },
  112: {
    id: 112,
    name: "npc_dota_hero_winter_wyvern",
    shortName: "winter_wyvern",
    displayName: "Winter Wyvern",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/winter_wyvern.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/winter_wyvern.png`,
  },
  113: {
    id: 113,
    name: "npc_dota_hero_arc_warden",
    shortName: "arc_warden",
    displayName: "Arc Warden",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/arc_warden.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/arc_warden.png`,
  },
  114: {
    id: 114,
    name: "npc_dota_hero_monkey_king",
    shortName: "monkey_king",
    displayName: "Monkey King",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/monkey_king.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/monkey_king.png`,
  },
  119: {
    id: 119,
    name: "npc_dota_hero_dark_willow",
    shortName: "dark_willow",
    displayName: "Dark Willow",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/dark_willow.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/dark_willow.png`,
  },
  120: {
    id: 120,
    name: "npc_dota_hero_pangolier",
    shortName: "pangolier",
    displayName: "Pangolier",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/pangolier.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/pangolier.png`,
  },
  121: {
    id: 121,
    name: "npc_dota_hero_grimstroke",
    shortName: "grimstroke",
    displayName: "Grimstroke",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/grimstroke.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/grimstroke.png`,
  },
  123: {
    id: 123,
    name: "npc_dota_hero_hoodwink",
    shortName: "hoodwink",
    displayName: "Hoodwink",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/hoodwink.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/hoodwink.png`,
  },
  126: {
    id: 126,
    name: "npc_dota_hero_void_spirit",
    shortName: "void_spirit",
    displayName: "Void Spirit",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/void_spirit.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/void_spirit.png`,
  },
  128: {
    id: 128,
    name: "npc_dota_hero_snapfire",
    shortName: "snapfire",
    displayName: "Snapfire",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/snapfire.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/snapfire.png`,
  },
  129: {
    id: 129,
    name: "npc_dota_hero_mars",
    shortName: "mars",
    displayName: "Mars",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/mars.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/mars.png`,
  },
  131: {
    id: 131,
    name: "npc_dota_hero_ringmaster",
    shortName: "ringmaster",
    displayName: "Ringmaster",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/ringmaster.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/ringmaster.png`,
  },
  135: {
    id: 135,
    name: "npc_dota_hero_dawnbreaker",
    shortName: "dawnbreaker",
    displayName: "Dawnbreaker",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/dawnbreaker.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/dawnbreaker.png`,
  },
  136: {
    id: 136,
    name: "npc_dota_hero_marci",
    shortName: "marci",
    displayName: "Marci",
    primaryAttr: "all",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/marci.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/marci.png`,
  },
  137: {
    id: 137,
    name: "npc_dota_hero_primal_beast",
    shortName: "primal_beast",
    displayName: "Primal Beast",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/primal_beast.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/primal_beast.png`,
  },
  138: {
    id: 138,
    name: "npc_dota_hero_muerta",
    shortName: "muerta",
    displayName: "Muerta",
    primaryAttr: "int",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/muerta.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/muerta.png`,
  },
  145: {
    id: 145,
    name: "npc_dota_hero_kez",
    shortName: "kez",
    displayName: "Kez",
    primaryAttr: "agi",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/kez.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/kez.png`,
  },
  155: {
    id: 155,
    name: "npc_dota_hero_largo",
    shortName: "largo",
    displayName: "Largo",
    primaryAttr: "str",
    roles: ["Carry", "Support"],
    avatarUrl: `${VALVE_HERO_IMG_BASE}/largo.png`,
    iconUrl: `${VALVE_HERO_IMG_BASE}/icons/largo.png`,
  },
};

/**
 * Returns hero metadata by ID, with dynamic fallback for unmapped or new upcoming heroes.
 */
export function getHero(heroId: number): HeroMetadata {
  if (HEROES_MAP[heroId]) {
    return HEROES_MAP[heroId];
  }

  const fallbackShort = `hero_${heroId}`;
  return {
    id: heroId,
    name: `npc_dota_hero_${fallbackShort}`,
    shortName: fallbackShort,
    displayName: `Hero #${heroId}`,
    primaryAttr: "all",
    roles: ["Flex"],
    avatarUrl: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/unknown.png",
    iconUrl: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/icons/unknown.png",
  };
}

export function registerDynamicHeroes(heroes: Array<Partial<HeroMetadata> & { id: number }>) {
  heroes.forEach((h) => {
    if (!h.id) return;
    HEROES_MAP[h.id] = {
      id: h.id,
      name: h.name || `npc_dota_hero_${h.shortName || h.id}`,
      shortName: h.shortName || `${h.id}`,
      displayName: h.displayName || h.name?.replace("npc_dota_hero_", "") || `Hero #${h.id}`,
      primaryAttr: (h.primaryAttr as "str" | "agi" | "int" | "all") || "all",
      roles: h.roles || ["Flex"],
      avatarUrl: h.avatarUrl || `${VALVE_HERO_IMG_BASE}/${h.shortName || "unknown"}.png`,
      iconUrl: h.iconUrl || `${VALVE_HERO_IMG_BASE}/icons/${h.shortName || "unknown"}.png`,
    };
  });
}
